# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: monitoring-CRD
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/prometheus-community/helm-charts.git
#     targetRevision: main
#     path: charts/kube-prometheus-stack/charts/crds/
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true