Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "sftp#{i}" do |sftp|
      sftp.vm.box = "ubuntu/jammy64"
      sftp.vm.hostname = "sftp#{i}"
      sftp.vm.provider "virtualbox" do |vb|
        vb.name = "sftp#{i}"
      end

      ip = "192.168.56.10#{i}"
      sftp.vm.network "private_network", ip: ip

      sftp.vm.synced_folder "./shared", "/home/vagrant/shared", create: true

      sftp.vm.provision "shell", path: "provision.sh", args: "#{i}"
    end
  end
end