Vagrant.configure("2") do |config|
  config.vm.define "alpine" do |alpine|
    alpine.vm.box = "generic/alpine318"
    alpine.vm.hostname = "alpine"

    alpine.vm.network "private_network", ip: "192.168.56.104"
    alpine.vm.network "forwarded_port", guest: 5000, host: 5000, auto_correct: true
    alpine.vm.synced_folder "shared", "/home/vagrant/shared", create: true

    alpine.vm.provision "shell", path: "setup_alpine.sh"

    alpine.vm.provision "shell", path: "alpine_ssh.sh", run: "never"
  end
  (1..3).each do |i|
    config.vm.define "sftp#{i}" do |sftp|
      sftp.vm.box = "ubuntu/jammy64"
      sftp.vm.hostname = "sftp#{i}"
      sftp.vm.provider "virtualbox" do |vb|
        vb.name = "sftp#{i}"
      end

      ip = "192.168.56.10#{i}"
      sftp.vm.network "private_network", ip: ip

      sftp.vm.synced_folder "shared", "/home/vagrant/shared", create: true

      sftp.vm.provision "shell", path: "provision.sh", args: "#{i}"

      sftp.vm.provision "shell", path: "systemd.sh", args: "#{i}"
    end
  end
end