---
- name: Ensure Nginx is installed and latest apt cache is used
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Copy SSL certificate
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/{{ item }}"
    owner: root
    group: root
    mode: "{{ '0600' if item.endswith('.key') else '0644' }}"
  loop:
    - ssl.com.key
    - ssl.com.pem
  become: yes

- name: Get backend and frontend Private IP
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:Name:
        - instance-frontend
        - instance-backend
      instance-state-name: running
  register: ec2_instances_info

- name: Set facts for private IPs
  set_fact:
    frontend_private_ip: "{{ ec2_instances_info.instances | selectattr('tags.Name', 'equalto', 'instance-frontend') | map(attribute='private_ip_address') | list | first }}"
    backend_private_ip: "{{ ec2_instances_info.instances | selectattr('tags.Name', 'equalto', 'instance-backend') | map(attribute='private_ip_address') | list | first }}"

- name: Create Nginx reverse proxy configuration
  template:
    src: reverse-proxy.conf.j2
    dest: /etc/nginx/sites-available/reverse-proxy
  become: yes

- name: Create symbolic link for reverse proxy configuration
  file:
    src: /etc/nginx/sites-available/reverse-proxy
    dest: /etc/nginx/sites-enabled/reverse-proxy
    state: link
  become: yes

- name: Remove default Nginx configuration
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  become: yes

- name: Reload Nginx service
  systemd:
    name: nginx
    state: reloaded
  become: yes
