---
- name: Run node_exporter container
  community.docker.docker_container:
    name: node-exporter
    image: prom/node-exporter:latest
    state: started
    restart_policy: unless-stopped
    network_mode: host
    pid_mode: host
    published_ports:
      - "9100:9100"
  become: true

- name: Run cAdvisor
  community.docker.docker_container:
    name: cAdvisor
    image: gcr.io/cadvisor/cadvisor:latest
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "9095:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
  become: true
