---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: true

- name: Install Docker if not present
  apt:
    name: docker.io
    state: present
    update_cache: true
  when: docker_check.rc != 0
  become: true

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
  when: docker_check.rc != 0
  become: true