- name: Fetch secret from AWS Secrets Manager
  set_fact:
    secret_obj: "{{ lookup('amazon.aws.aws_secret', secret_name, region=region) | from_json }}"

- name: Set DB facts
  set_fact:
    db_name: "{{ secret_obj.db_name }}"
    db_user: "{{ secret_obj.db_username }}"
    db_password: "{{ secret_obj.db_password }}"
    MAIN_DOMAIN: "{{ secret_obj.domain }}"

- name: Copy secrets.yml from template
  template:
    src: secrets.yml.j2
    dest: /home/{{ user }}/secrets.yml
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Apply secrets.yml
  shell: kubectl apply -f /home/{{ user }}/secrets.yml
  args:
    executable: /bin/bash
