---
- name: Copy argocd folder
  copy:
    src: argocd/
    dest: /home/{{ user }}/argocd/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Apply argocd ingress
  shell: kubectl apply -f /home/{{ user }}/argocd/ingress.yml -n argocd
  args:
    executable: /bin/bash
  
- name: install ArgoCD
  shell: |
    helm repo add argo https://argoproj.github.io/argo-helm
    helm repo update
    helm install argocd argo/argo-cd --namespace argocd -f /home/{{ user }}/argocd/argo-values.yml
  environment:
    KUBECONFIG: "/home/{{ user }}/.kube/config"
  args:
    executable: /bin/bash

- name: install ArgoCD cli
  shell: |
    VERSION=$(curl -s https://api.github.com/repos/argoproj/argo-cd/releases/latest | grep tag_name | cut -d '"' -f 4)
    curl -LO https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-amd64
    chmod +x argocd-linux-amd64
    sudo mv argocd-linux-amd64 /usr/local/bin/argocd
    sleep 25
  args:
    executable: /bin/bash

- name: configure ArgoCD
  shell: |
    pass=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
    echo $pass
    argocd login argo.proxy-test.xyz --username admin --password $pass
    argocd repo add https://github.com/NightPhoenixSC2/ArgoCD.git --username NightPhoenixSC2 --password {{ GITHUB_TOKEN }}
    kubectl apply -f /home/{{ user }}/argocd/root.yml -n argocd
  environment:
    KUBECONFIG: "/home/{{ user }}/.kube/config"
  args:
    executable: /bin/bash
