apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config-frontend
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-gateway.default.svc.cluster.local/loki/api/v1/push
        tenant_id: foo
    scrape_configs:
      - job_name: frontend
        static_configs:
          - targets: ['localhost']
            labels:
              job: frontend
              service_name: frontend
              __path__: /var/log/nginx/*.log
