apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-gateway.default.svc.cluster.local/loki/api/v1/push
        tenant_id: foo
        
    scrape_configs:
      - job_name: tomcat-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: backend
              __path__: /opt/tomcat/logs/*.log
