---
- hosts: server
  become: true
  roles:
    - server-init

- hosts: worker-node-1,worker-node-2,worker-node-3
  become: true
  vars:
    k3s_node_token: "{{ hostvars[groups['server'][0]]['k3s_node_token'] }}"
  roles:
    - worker-init

- hosts: server
  collections:
    - amazon.aws
  vars:
    DATABASE_ENDPOINT: "{{ lookup('env', 'DATABASE_ENDPOINT') }}"
    secret_name: "{{ lookup('env', 'SECRET_NAME') }}"
    s3_bucket: "{{ lookup('env', 'S3_BUCKET_NAME') }}"
    region: "us-east-1"
    s3_object_key: "Dump/database.sql"
    s3_dest_path: "./database.sql"
  become: yes
  gather_facts: no
  roles:
    - ssl
    - dump
    - secrets

- hosts: server
  become: true
  roles:
    - install-helm
    - install-metallb
    - worker-roles
    - argocd
    - crds
    - monitoring
