- name: Copy secrets.yml from template
  template:
    src: secrets.yml.j2
    dest: /home/{{ user }}/secrets.yml
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"

- name: Apply secrets.yml
  shell: kubectl apply -f /home/{{ user }}/secrets.yml
  args:
    executable: /bin/bash
