pipeline {
    agent any

    parameters {
            booleanParam(name: 'AUTO_RUN_CD', defaultValue: false)
        }

    tools {
        jdk 'jdk11'
        gradle 'gradle-6.9.4'
    }

    stages {
        stage('Checkout from GitHub') {
            steps {
                git branch: 'main',
			    url: 'https://github.com/NightPhoenixSC2/jenkins-test.git',
		    	credentialsId: 'git'
            }
        }

        stage('Build Frontend') {
            tools {
                nodejs 'Node14'
            }
            environment {
                REACT_APP_API_BASE_URL = 'DOMAIN_TOKEN'
            }
            steps {
                dir('frontend-project') {
                    dir ('frontend') {
                        script {
                            sh 'npm install'
                            sh 'npm run build'
                        }
                    }
                }
            }
        }

        stage('Frontend Code Review') {
            environment {
                PROJECT_KEY = 'class-schedule-frontend'
                BUILD_VERSION = '1.0' // set build version
                SONAR_TOKEN = credentials('SONAR_TOKEN')
                SONAR_URL = credentials('SONAR_URL')
            }
            steps {
                dir('frontend-project/frontend/') {
                    script {
                        sh 'sed -i -e "s|PROJECT_KEY|${PROJECT_KEY}|g" \
                            -e "s|BUILD_VERSION|${BUILD_VERSION}|g" \
                            -e "s|SONAR_TOKEN|${SONAR_TOKEN}|g" \
                            -e "s|SONAR_URL|${SONAR_URL}|g" "sonar-project.properties"'
                        sh 'sonar-scanner'
                    }
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {
                dir('frontend-project') {
                    script {
                        sh 'cp -r frontend/build ./build'
                        sh 'docker build -t frontend-test:latest .' // change "latest" to version
                    }
                }
            }
        }
        
        stage('Move Docker Image to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_TOKEN')]) {
                    sh '''
                        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
                        docker tag frontend-test:latest $DOCKERHUB_USERNAME/4947-frontend:latest
                        docker push $DOCKERHUB_USERNAME/4947-frontend:latest
                    '''
                }
            }
        }
    }
}