---
- name: Copy monitoring folder
  copy:
    src: monitoring/
    dest: /home/{{ user }}/monitoring/
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"

- name: Apply Loki dashboard
  shell: kubectl apply -f /home/{{ user }}/monitoring/templates/loki-basic-dashboard.yaml
  args:
    executable: /bin/bash
