---
- name: Ensure Nginx is installed and latest apt cache is used
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Copy SSL certificate
  copy:
    src: "{{ item }}"
    dest: "/etc/ssl/{{ item }}"
    owner: root
    group: root
    mode: "{{ '0600' if item.endswith('.key') else '0644' }}"
  loop:
    - ssl.com.key
    - ssl.com.pem
  become: yes

- name: Create Nginx monitoring configuration
  template:
    src: monitoring.conf.j2
    dest: /etc/nginx/sites-available/monitoring
  become: yes

- name: Create symbolic link for monitoring configuration
  file:
    src: /etc/nginx/sites-available/monitoring
    dest: /etc/nginx/sites-enabled/monitoring
    state: link
  become: yes

- name: Remove default Nginx configuration
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  notify: Reload Nginx
  become: yes